### PR TITLE
Add direct instruction about installing Xcode Developer Tools

### PR DESCRIPTION
**Pull request by thSoft**
Related to #2

### CODE REVIEW

**Comment by ben-z** [comment]
Oops I missed this PR!

The [resolution](https://github.com/ben-z/free-sidecar/issues/2#issuecomment-548904044) for #2 is downloading Xcode from the App Store. Can we update the instructions to reflect that?

**Comment by xichens** [comment]
Does it require the full Xcode or CLT is enough?

**Comment by ben-z** [comment]
CLT should be enough

**Comment by ben-z** [comment]
https://github.com/ben-z/free-sidecar/commit/a7b20b323dc3d628648ee58e8507391d1cd9b976 should be sufficient

**Pull request closed without merging**
